<?php

const RESPONSE_STATUS_CREATED = 201;
const RESPONSE_STATUS_SUCCESS = 200;
const RESPONSE_STATUS_BAD_REQUEST = 400;
const RESPONSE_STATUS_NOT_FOUND = 404;
const RESPONSE_STATUS_UNPROCESSABLE_ENTITY = 422;
const RESPONSE_STATUS_INTERNAL_SERVER_ERROR = 422;